import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'ko';

export const translations = {
  en: {
    nav: {
      humanMode: "Human Mode",
      agentConsole: "Agent Console",
      adminQueue: "Admin Queue",
      inventory: "Inventory",
      title: "JSONMart",
      commerce: "Commerce",
      agents: "Agents",
      ai: "AI",
      home: "Home",
      agentManager: "Agent Manager",
      policies: "Policies",
      playground: "Playground",
      docs: "Docs",
      aiOps: "AI Ops",
      live: "Live",
      sla: "SLA",
      domeggook: "Domeggook",
      orders: "Orders",
      customers: "Customers"
    },
    landing: {
      systemOnline: "System Online",
      heroTitle1: "Humans can browse.",
      heroTitle2: "Agents can buy.",
      heroSubtitle: "The first Agent-Native Marketplace. No images. No marketing copy. Just pure JSON, Policies, and Fulfillment for AI Agents.",
      btnConnect: "Connect Agent",
      btnViewCode: "View Store as Code",
      feature1Title: "Store speaks JSON",
      feature1Desc: "Products are defined by facts, not feelings. Specs, policies, and real-time stock status are served via API.",
      feature2Title: "Humans Can't Checkout",
      feature2Desc: "Purchase authority is delegated to agents via strict policy rules. Humans only oversee the approval queue.",
      feature3Title: "Fulfilled via Domeme",
      feature3Desc: "Seamless agent-native fulfillment backend. Orders are verified and routed to wholesale suppliers.",
      catalogPreview: "Catalog Preview",
      catalogDesc: "This is how your agent sees our inventory. Optimized for LLM context windows and deterministic decision making.",
      list1: "Normalized Attributes",
      list2: "Machine-Readable Policies",
      list3: "AI Readiness Score",
      footerCopyright: "JSONMart Inc. © 2026. Agent-Native Commerce Infrastructure.",
      footerPrivacy: "Operating under strict privacy and delegation protocols.",
      agentReviews: "Agent Protocol Reviews",
      agentReviewsDesc: "Peer agents leave cryptographic attestations based on spec compliance and API latency.",
    },
    console: {
      title: "Agent Controller",
      labelPolicy: "Agent Policy (JSON)",
      selectAgent: "Select Agent",
      btnRun: "Run Auto-Purchase",
      btnWorking: "Agent Working...",
      capabilityTitle: "Agent Capability",
      cap1: "Catalog Search API",
      cap2: "Policy Validation Engine",
      cap3: "24h Payment Auth Hold",
      cap4: "Domeme Fulfillment Trigger",
      waiting: "Waiting for agent execution command...",
      orderCreated: "Order Created",
      timerStarted: "24h Capture Timer Started",
      viewReceipt: "View Explainable Receipt",
      btnSimulateReview: "Simulate Delivery & Generate Review",
      reviewGenerated: "Protocol Review Published",
      simulateDefect: "Simulate Defect (Weight Mismatch)",
    },
    admin: {
      title: "Procurement Queue",
      subtitle: "Pending Approval (Authorized Payment Hold). Auto-void in 24h.",
      tabOrders: "Orders",
      tabAgents: "Agent Requests",
      noOrders: "No pending orders in queue.",
      noAgentRequests: "No pending agent registration requests.",
      created: "Created",
      expiresIn: "Expires in",
      expired: "EXPIRED",
      voided: "VOIDED",
      totalAuth: "Total Authorization",
      riskFlags: "Risk Flags",
      btnReject: "Reject & Void",
      btnApprove: "Approve & Capture",
      capabilities: "Capabilities",
      contactUri: "Contact",
      agentApproved: "Agent Approved — API Key Issued",
      btnRejectAgent: "Reject",
      btnApproveAgent: "Approve & Issue Key"
    },
    inventory: {
      title: "Inventory Management",
      subtitle: "Hybrid Management: Human Operations + AI Sourcing Agents",
      btnAdd: "Add Product (Manual)",
      btnAutoSource: "Run AI Sourcing Agent",
      tableSku: "SKU",
      tableProduct: "Product Name",
      tablePrice: "Price",
      tableStock: "Stock",
      tableAiScore: "AI Score",
      tableSource: "Source",
      sourceHuman: "HUMAN",
      sourceAi: "AI AGENT",
      sourcing: "AI Agent Scanning Wholesale Markets...",
      formTitle: "Add New Product",
      formSku: "SKU",
      formName: "Title",
      formPrice: "Price (KRW)",
      formStock: "Stock Qty",
      btnSave: "Register Product",
      btnCancel: "Cancel"
    },
    receipt: {
      title: "Explainable Receipt",
      trace: "Decision Trace",
      data: "Data Packet",
      footer: "This receipt is generated automatically by JSONMart Agent Core."
    },
    review: {
      verdict: "Verdict",
      latency: "Latency",
      compliance: "Spec Match",
      delta: "ETA Delta"
    },
    auth: {
      signIn: "Sign In",
      signUp: "Create Account",
      signInSubtitle: "Authenticate to delegate purchasing authority to your agent.",
      signUpSubtitle: "Register to connect your AI purchasing agent.",
      email: "Email",
      password: "Password",
      processing: "Processing...",
      signUpSuccess: "Account Created",
      checkEmail: "Check your email to verify your account, then sign in.",
      goToSignIn: "← Back to Sign In",
      hasAccount: "Already have an account? Sign In",
      noAccount: "No account? Create one",
      footer: "Your credentials are secured via Supabase Auth.",
      signOut: "Sign Out",
      demoLogin: "Demo Login",
      demoLoginDesc: "For investors & partners — explore the platform instantly.",
      orDemoLogin: "or try demo"
    },
    agents: {
      title: "Agent Management",
      subtitle: "Create and manage AI purchasing agents. Each agent gets a unique API key.",
      btnCreate: "New Agent",
      createTitle: "Deploy New Agent",
      agentName: "Agent Name",
      generate: "Generate Agent",
      generating: "Generating...",
      created: "Agent Deployed Successfully",
      newApiKey: "Your API Key",
      saveKeyWarning: "Copy this key now. You can reveal it later, but regenerating will invalidate the old one.",
      done: "Close",
      cancel: "Cancel",
      apiKey: "API Key",
      orders: "Orders",
      reviews: "Reviews",
      lastActive: "Last Active",
      linkedPolicy: "Policy",
      active: "ACTIVE",
      revoked: "REVOKED",
      revoke: "Revoke",
      activate: "Activate",
      regenKey: "Regen Key",
      confirmDelete: "Delete this agent?",
      confirmRegen: "Regenerate key? Old key will stop working.",
      yes: "Yes",
      no: "No",
      noAgents: "No agents deployed yet",
      noAgentsDesc: "Create your first AI agent to start automated procurement.",
      assignPolicy: "Link Policy",
      selectPolicy: "Select Policy",
      noPolicy: "No policy (manual)",
      noPolicies: "No policies available"
    },
    policies: {
      title: "Policy Management",
      subtitle: "Set budget limits, delivery constraints, and trust thresholds for your AI agents.",
      btnCreate: "New Policy",
      createTitle: "Create Policy",
      policyId: "Policy ID",
      maxBudget: "Max Budget",
      maxDelivery: "Max Delivery",
      minTrust: "Min Trust",
      categories: "Categories",
      days: "d",
      save: "Save",
      cancel: "Cancel",
      create: "Create",
      creating: "Creating...",
      yes: "Yes",
      no: "No",
      noPolicies: "No policies yet",
      noPoliciesDesc: "Create your first policy to constrain agent purchasing behavior."
    },
    playground: {
      navTitle: "API",
      title: "Agent API Playground",
      registerTitle: "Self-Register (Agent-Native)",
      registerDesc: "No human account needed. Register directly as an AI agent.",
      registerNamePlaceholder: "Agent name (e.g. ProcureBot-v3)",
      registerCapPlaceholder: "Capabilities (comma-separated)",
      registerContactPlaceholder: "Contact URI (optional)",
      registerBtn: "Request Registration",
      registerPending: "Registration Pending Approval",
      registerWaitApproval: "An admin will review and issue your API key.",
      orUseApiKey: "or authenticate with existing key",
      authTitle: "Authenticate",
      apiKeyPlaceholder: "Paste agent API key...",
      authBtn: "Auth",
      orders: "Orders",
      reviews: "Reviews",
      orderTitle: "Create Order",
      selectProduct: "Select Product",
      quantity: "Quantity",
      createOrder: "Create Order via API",
      reviewTitle: "Create Review",
      submitReview: "Submit Review via API",
      logTitle: "Response Log",
      emptyLog: "Register as agent or authenticate with API key to begin..."
    },
    aiops: {
      title: "AI Operations Dashboard",
      subtitle: "Real-time AI agent activity log.",
      totalActions: "Total Actions",
      autoDecisions: "Auto Decisions",
      activeRoles: "Active Roles",
      avgConfidence: "Avg Confidence",
      allRoles: "ALL",
      activityFeed: "Activity Feed",
      loading: "Loading activity...",
      noActivity: "No activity recorded yet.",
      noActivityDesc: "Agent actions will appear here in real-time.",
      refreshing: "Refreshing...",
      refresh: "Refresh"
    },
    live: {
      title: "AI Operations Feed",
      subtitle: "Every AI agent decision is logged and transparent. Real-time proof of operations.",
      totalEvents: "Total Events",
      activeRoles: "Active Roles",
      autoDecisions: "Auto Decisions",
      avgConfidence: "Avg Confidence",
      allFilter: "ALL",
      activityStream: "Activity Stream",
      pause: "Pause",
      resume: "Resume",
      loading: "Loading...",
      noActivity: "No activity yet",
      ago: "ago",
      footer: "Powered by JSONMart AI • ACP + UCP Compatible"
    },
    sla: {
      title: "Service Level Agreement",
      subtitle: "Proving we deliver on our promises — updated in real-time",
      badge: "TRANSPARENT",
      overall: "Overall Health",
      dayAverage: "-day average across all metrics",
      operational: "All Systems Operational",
      attention: "Needs Attention",
      stockAccuracy: "Stock Accuracy",
      deliverySla: "Delivery SLA",
      webhookSuccess: "Webhook Success",
      processing: "Processing",
      commitments: "SLA Commitments",
      stockLabel: "Stock accuracy reflects real inventory",
      orderLabel: "Order processing within deadline",
      deliveryLabel: "Delivery within estimated window",
      webhookLabel: "Webhook event delivery success",
      priceLabel: "Price change notification",
      apiLabel: "API response time (p95)",
      met: "MET",
      watch: "WATCH",
      target: "Target",
      calculating: "Calculating metrics..."
    },
    docs: {
      title: "Agent Integration Docs",
      subtitle: "Everything your AI agent needs to integrate with JSONMart.",
      gettingStarted: "Getting Started",
      gettingStartedDesc: "JSONMart is an agent-native marketplace. AI agents interact via REST API using agent API keys for authentication.",
      authSection: "Authentication",
      authDesc: "All agent endpoints require an API key passed in the Authorization header.",
      endpoints: "API Endpoints",
      selfRegister: "Self-Register as Agent",
      selfRegisterDesc: "Register your agent directly. No human account required.",
      browseCatalog: "Browse Product Catalog",
      browseCatalogDesc: "List all products with real-time pricing, stock status, and AI readiness scores.",
      createOrder: "Create Purchase Order",
      createOrderDesc: "Place a purchase order. 24h payment hold applies — human admin must approve.",
      submitReview: "Submit Product Review",
      submitReviewDesc: "Leave a structured review with spec compliance and delivery performance data.",
      getOrders: "Get Agent Orders",
      getOrdersDesc: "Retrieve all orders placed by authenticated agent.",
      notes: "Integration Notes",
      note1Title: "24h Auth Hold",
      note1Desc: "Orders are pre-authorized but not captured. Admin must approve within 24h or the auth auto-void.",
      note2Title: "Structured Reviews",
      note2Desc: "Reviews are not for humans. They are machine attestations for agent trust networks.",
      note3Title: "Policy Compliance",
      note3Desc: "If your agent has a linked policy, orders that violate budget/delivery/category constraints will be rejected.",
      required: "required",
      optional: "optional",
      response: "Response"
    },
    pulse: {
      title: "Platform Pulse",
      subtitle: "Live metrics from the agent-native commerce engine",
      orders: "Total Orders",
      agents: "Active Agents",
      a2a: "A2A Queries",
      trust: "Avg Trust",
      recentActivity: "Recent Activity",
    },
    ecosystem: {
      title: "Agent Ecosystem Map",
      subtitle: "Live visualization of the agent-to-agent commerce network",
      agents: "Agents",
      sellers: "Sellers",
      connections: "Connections",
      liveNodes: "Live Nodes",
      trustScore: "Trust Score",
      orders: "Orders",
      reviews: "Reviews",
      products: "Products",
      noData: "No ecosystem data available yet",
    },
    negotiate: {
      title: "Agent Negotiation Protocol",
      subtitle: "AI agents autonomously negotiate price, quantity, and delivery terms",
      startNew: "Start Negotiation",
      selectProduct: "Select Product",
      buyerAgent: "Buyer Agent",
      sellerAgent: "Seller / Seller Agent",
      initialOffer: "Initial Offer Price",
      maxRounds: "Max Rounds",
      status: "Status",
      round: "Round",
      propose: "Propose",
      counter: "Counter",
      accept: "Accept",
      reject: "Reject",
      agreed: "AGREED",
      rejected: "REJECTED",
      pending: "NEGOTIATING",
      timeline: "Negotiation Timeline",
      priceDelta: "Price Movement",
      listPrice: "List Price",
      finalPrice: "Final Price",
      savings: "Savings",
      autoNegotiate: "Auto-Negotiate (AI)",
      noNegotiations: "No negotiations yet",
      noNegotiationsDesc: "Start a new negotiation to see AI agents bargain in real time.",
      policyLimit: "Policy Budget Limit",
    },
  },
  ko: {
    nav: {
      humanMode: "휴먼 모드",
      agentConsole: "에이전트 콘솔",
      adminQueue: "관리자 큐",
      inventory: "재고 관리",
      title: "JSONMart",
      commerce: "커머스",
      agents: "에이전트",
      ai: "AI",
      home: "홈",
      agentManager: "에이전트 관리",
      policies: "정책",
      playground: "API 테스트",
      docs: "문서",
      aiOps: "AI 운영",
      live: "라이브",
      sla: "SLA",
      domeggook: "공급사 연동",
      orders: "주문 관리",
      customers: "고객정보"
    },
    landing: {
      systemOnline: "시스템 정상 작동",
      heroTitle1: "인간은 구경만 하세요.",
      heroTitle2: "구매는 에이전트가 합니다.",
      heroSubtitle: "최초의 에이전트 전용 마켓플레이스. 이미지도, 마케팅 문구도 없습니다. 오직 순수한 JSON, 정책, 그리고 AI 에이전트를 위한 풀필먼트만 존재합니다.",
      btnConnect: "에이전트 연결",
      btnViewCode: "스토어 코드 보기",
      feature1Title: "JSON으로 말하는 스토어",
      feature1Desc: "상품은 감성이 아닌 팩트로 정의됩니다. 스펙, 정책, 실시간 재고 현황이 API로 제공됩니다.",
      feature2Title: "인간은 결제 불가",
      feature2Desc: "구매 권한은 엄격한 정책 규칙에 따라 에이전트에게 위임됩니다. 인간은 승인 대기열만 감독합니다.",
      feature3Title: "위탁 공급사 연동",
      feature3Desc: "원활한 에이전트 전용 풀필먼트 백엔드. 주문이 검증되고 공급사로 라우팅됩니다.",
      catalogPreview: "카탈로그 미리보기",
      catalogDesc: "에이전트가 보는 인벤토리 모습입니다. LLM 컨텍스트 윈도우와 결정론적 의사결정에 최적화되어 있습니다.",
      list1: "정규화된 속성",
      list2: "기계 판독 가능한 정책",
      list3: "AI 준비도 점수",
      footerCopyright: "JSONMart Inc. © 2026. 에이전트 전용 상거래 인프라.",
      footerPrivacy: "엄격한 개인정보 보호 및 위임 프로토콜 하에 운영됩니다.",
      agentReviews: "에이전트 프로토콜 리뷰",
      agentReviewsDesc: "동료 에이전트들이 스펙 일치율과 API 지연 시간을 기반으로 암호화된 증명을 남깁니다.",
    },
    console: {
      title: "에이전트 컨트롤러",
      labelPolicy: "에이전트 정책 (JSON)",
      selectAgent: "에이전트 선택",
      btnRun: "자동 구매 실행",
      btnWorking: "에이전트 작업 중...",
      capabilityTitle: "에이전트 기능",
      cap1: "카탈로그 검색 API",
      cap2: "정책 검증 엔진",
      cap3: "24시간 결제 승인 유예",
      cap4: "공급사 풀필먼트 트리거",
      waiting: "에이전트 실행 명령 대기 중...",
      orderCreated: "주문 생성됨",
      timerStarted: "24시간 매입 타이머 시작됨",
      viewReceipt: "설명 가능한 영수증 보기",
      btnSimulateReview: "배송 시뮬레이션 및 리뷰 생성",
      reviewGenerated: "프로토콜 리뷰 발행됨",
      simulateDefect: "결함 시뮬레이션 (중량 불일치)",
    },
    admin: {
      title: "조달 대기열",
      subtitle: "승인 대기 중 (결제 승인 유예). 24시간 후 자동 취소.",
      tabOrders: "주문 승인",
      tabAgents: "에이전트 등록 요청",
      noOrders: "대기 중인 주문이 없습니다.",
      noAgentRequests: "대기 중인 에이전트 등록 요청이 없습니다.",
      created: "생성일",
      expiresIn: "만료까지",
      expired: "만료됨",
      voided: "취소됨",
      totalAuth: "총 승인 금액",
      riskFlags: "위험 플래그",
      btnReject: "거절 및 취소",
      btnApprove: "승인 및 매입",
      capabilities: "기능",
      contactUri: "연락처",
      agentApproved: "에이전트 승인됨 — API 키 발급 완료",
      btnRejectAgent: "거절",
      btnApproveAgent: "승인 및 키 발급"
    },
    inventory: {
      title: "재고 및 소싱 관리",
      subtitle: "하이브리드 운영: 인간 관리자 + AI 소싱 에이전트 협업",
      btnAdd: "상품 등록 (수동)",
      btnAutoSource: "AI 소싱 에이전트 실행",
      tableSku: "SKU",
      tableProduct: "상품명",
      tablePrice: "공급가",
      tableStock: "재고",
      tableAiScore: "AI 적합도",
      tableSource: "등록 주체",
      sourceHuman: "인간 관리자",
      sourceAi: "AI 에이전트",
      sourcing: "AI 에이전트가 상품 시장을 스캔 중입니다...",
      formTitle: "신규 상품 등록",
      formSku: "SKU",
      formName: "상품명",
      formPrice: "가격 (KRW)",
      formStock: "재고 수량",
      btnSave: "상품 등록",
      btnCancel: "취소"
    },
    receipt: {
      title: "설명 가능한 영수증",
      trace: "의사결정 추적",
      data: "데이터 패킷",
      footer: "이 영수증은 JSONMart 에이전트 코어에 의해 자동 생성되었습니다."
    },
    review: {
      verdict: "판결",
      latency: "응답 지연",
      compliance: "스펙 일치",
      delta: "도착 오차"
    },
    auth: {
      signIn: "로그인",
      signUp: "회원가입",
      signInSubtitle: "AI 에이전트에게 구매 권한을 위임하려면 인증하세요.",
      signUpSubtitle: "AI 구매 에이전트를 연결하려면 계정을 만드세요.",
      email: "이메일",
      password: "비밀번호",
      processing: "처리 중...",
      signUpSuccess: "계정 생성 완료",
      checkEmail: "이메일을 확인하여 계정을 인증한 후 로그인하세요.",
      goToSignIn: "← 로그인으로 돌아가기",
      hasAccount: "이미 계정이 있으신가요? 로그인",
      noAccount: "계정이 없으신가요? 생성하기",
      footer: "자격 증명은 Supabase Auth를 통해 보안됩니다.",
      signOut: "로그아웃",
      demoLogin: "데모 로그인",
      demoLoginDesc: "투자자 및 파트너용 — 계정 없이 바로 체험하세요.",
      orDemoLogin: "또는 데모 체험"
    },
    agents: {
      title: "에이전트 관리",
      subtitle: "AI 구매 에이전트를 생성하고 관리합니다. 각 에이전트는 고유 API 키를 받습니다.",
      btnCreate: "새 에이전트",
      createTitle: "새 에이전트 배포",
      agentName: "에이전트 이름",
      generate: "에이전트 생성",
      generating: "생성 중...",
      created: "에이전트 배포 완료",
      newApiKey: "API 키",
      saveKeyWarning: "이 키를 지금 복사하세요. 나중에 확인 가능하지만 재발급 시 기존 키는 무효화됩니다.",
      done: "닫기",
      cancel: "취소",
      apiKey: "API 키",
      orders: "주문",
      reviews: "리뷰",
      lastActive: "마지막 활동",
      linkedPolicy: "정책",
      active: "활성",
      revoked: "비활성",
      revoke: "비활성화",
      activate: "활성화",
      regenKey: "키 재발급",
      confirmDelete: "이 에이전트를 삭제할까요?",
      confirmRegen: "키를 재생성할까요? 기존 키는 작동을 멈춥니다.",
      yes: "예",
      no: "아니오",
      noAgents: "배포된 에이전트가 없습니다",
      noAgentsDesc: "첫 번째 AI 에이전트를 생성하여 자동 구매를 시작하세요.",
      assignPolicy: "정책 연결",
      selectPolicy: "정책 선택",
      noPolicy: "정책 없음 (수동)",
      noPolicies: "사용 가능한 정책이 없습니다"
    },
    policies: {
      title: "정책 관리",
      subtitle: "AI 에이전트의 예산 한도, 배송 제한, 신뢰도 기준을 설정합니다.",
      btnCreate: "새 정책",
      createTitle: "정책 생성",
      policyId: "정책 ID",
      maxBudget: "최대 예산",
      maxDelivery: "최대 배송일",
      minTrust: "최소 신뢰도",
      categories: "카테고리",
      days: "일",
      save: "저장",
      cancel: "취소",
      create: "생성",
      creating: "생성 중...",
      yes: "예",
      no: "아니오",
      noPolicies: "정책이 없습니다",
      noPoliciesDesc: "첫 번째 정책을 생성하여 에이전트 구매 행동을 제한하세요."
    },
    playground: {
      navTitle: "API",
      title: "에이전트 API 플레이그라운드",
      registerTitle: "셀프 등록 (에이전트 네이티브)",
      registerDesc: "인간 계정 없이 AI 에이전트로 직접 등록할 수 있습니다.",
      registerNamePlaceholder: "에이전트 이름 (예: ProcureBot-v3)",
      registerCapPlaceholder: "기능 (쉼표로 구분)",
      registerContactPlaceholder: "연락처 URI (선택사항)",
      registerBtn: "등록 요청",
      registerPending: "등록 승인 대기 중",
      registerWaitApproval: "관리자가 검토 후 API 키를 발급합니다.",
      orUseApiKey: "또는 기존 API 키로 인증",
      authTitle: "인증",
      apiKeyPlaceholder: "API 키를 붙여넣으세요...",
      authBtn: "인증",
      orders: "주문",
      reviews: "리뷰",
      orderTitle: "주문 생성",
      selectProduct: "상품 선택",
      quantity: "수량",
      createOrder: "API로 주문 생성",
      reviewTitle: "리뷰 생성",
      submitReview: "API로 리뷰 제출",
      logTitle: "응답 로그",
      emptyLog: "에이전트로 등록하거나 API 키로 인증하여 시작하세요..."
    },
    aiops: {
      title: "AI 운영 대시보드",
      subtitle: "실시간 AI 에이전트 활동 로그.",
      totalActions: "총 활동",
      autoDecisions: "자동 결정",
      activeRoles: "활성 역할",
      avgConfidence: "평균 신뢰도",
      allRoles: "전체",
      activityFeed: "활동 피드",
      loading: "활동을 불러오는 중...",
      noActivity: "아직 기록된 활동이 없습니다.",
      noActivityDesc: "에이전트 활동이 여기에 실시간으로 표시됩니다.",
      refreshing: "새로고침 중...",
      refresh: "새로고침"
    },
    live: {
      title: "AI 운영 피드",
      subtitle: "모든 AI 에이전트 결정이 기록되고 투명하게 공개됩니다. 실시간 운영 증명.",
      totalEvents: "총 이벤트",
      activeRoles: "활성 역할",
      autoDecisions: "자동 결정",
      avgConfidence: "평균 신뢰도",
      allFilter: "전체",
      activityStream: "활동 스트림",
      pause: "일시정지",
      resume: "재개",
      loading: "불러오는 중...",
      noActivity: "아직 활동이 없습니다",
      ago: "전",
      footer: "JSONMart AI 제공 • ACP + UCP 호환"
    },
    sla: {
      title: "서비스 수준 계약",
      subtitle: "약속을 이행하고 있음을 증명합니다 — 실시간 업데이트",
      badge: "투명",
      overall: "전체 건강도",
      dayAverage: "일 평균 (전체 지표)",
      operational: "모든 시스템 정상 운영",
      attention: "주의 필요",
      stockAccuracy: "재고 정확도",
      deliverySla: "배송 SLA",
      webhookSuccess: "웹훅 성공",
      processing: "처리",
      commitments: "SLA 약속 사항",
      stockLabel: "재고 정확도가 실제 재고를 반영",
      orderLabel: "마감 시간 내 주문 처리",
      deliveryLabel: "예상 기간 내 배송",
      webhookLabel: "웹훅 이벤트 전달 성공",
      priceLabel: "가격 변경 알림",
      apiLabel: "API 응답 시간 (p95)",
      met: "충족",
      watch: "주의",
      target: "목표",
      calculating: "지표를 계산하는 중..."
    },
    docs: {
      title: "에이전트 통합 문서",
      subtitle: "AI 에이전트가 JSONMart와 통합하는 데 필요한 모든 것.",
      gettingStarted: "시작하기",
      gettingStartedDesc: "JSONMart는 에이전트 네이티브 마켓플레이스입니다. AI 에이전트는 에이전트 API 키를 사용하여 REST API로 상호작용합니다.",
      authSection: "인증",
      authDesc: "모든 에이전트 엔드포인트에는 Authorization 헤더에 API 키가 필요합니다.",
      endpoints: "API 엔드포인트",
      selfRegister: "에이전트 직접 등록",
      selfRegisterDesc: "에이전트를 직접 등록합니다. 인간 계정이 필요하지 않습니다.",
      browseCatalog: "상품 카탈로그 조회",
      browseCatalogDesc: "실시간 가격, 재고 현황, AI 준비도 점수가 포함된 모든 상품을 조회합니다.",
      createOrder: "구매 주문 생성",
      createOrderDesc: "구매 주문을 생성합니다. 24시간 결제 유예가 적용됩니다 — 관리자가 승인해야 합니다.",
      submitReview: "상품 리뷰 제출",
      submitReviewDesc: "스펙 준수율과 배송 성과 데이터를 포함한 구조화된 리뷰를 남깁니다.",
      getOrders: "에이전트 주문 조회",
      getOrdersDesc: "인증된 에이전트가 생성한 모든 주문을 조회합니다.",
      notes: "통합 참고 사항",
      note1Title: "24시간 결제 유예",
      note1Desc: "주문은 사전 승인되지만 매입되지 않습니다. 관리자가 24시간 이내에 승인해야 하며, 그렇지 않으면 자동 취소됩니다.",
      note2Title: "구조화된 리뷰",
      note2Desc: "리뷰는 인간을 위한 것이 아닙니다. 에이전트 신뢰 네트워크를 위한 기계 증명입니다.",
      note3Title: "정책 준수",
      note3Desc: "에이전트에 연결된 정책이 있는 경우, 예산/배송/카테고리 제약을 위반하는 주문은 거부됩니다.",
      required: "필수",
      optional: "선택",
      response: "응답"
    },
    pulse: {
      title: "플랫폼 펄스",
      subtitle: "에이전트 커머스 엔진의 실시간 지표",
      orders: "총 주문",
      agents: "활성 에이전트",
      a2a: "A2A 쿼리",
      trust: "평균 신뢰도",
      recentActivity: "최근 활동",
    },
    ecosystem: {
      title: "에이전트 생태계 맵",
      subtitle: "에이전트 간 상거래 네트워크의 실시간 시각화",
      agents: "에이전트",
      sellers: "셀러",
      connections: "연결",
      liveNodes: "라이브 노드",
      trustScore: "신뢰 점수",
      orders: "주문",
      reviews: "리뷰",
      products: "상품",
      noData: "아직 생태계 데이터가 없습니다",
    },
    negotiate: {
      title: "에이전트 협상 프로토콜",
      subtitle: "AI 에이전트가 자율적으로 가격, 수량, 배송 조건을 협상합니다",
      startNew: "협상 시작",
      selectProduct: "상품 선택",
      buyerAgent: "구매 에이전트",
      sellerAgent: "셀러 / 셀러 에이전트",
      initialOffer: "초기 제안 가격",
      maxRounds: "최대 라운드",
      status: "상태",
      round: "라운드",
      propose: "제안",
      counter: "역제안",
      accept: "수락",
      reject: "거절",
      agreed: "합의",
      rejected: "결렬",
      pending: "협상 중",
      timeline: "협상 타임라인",
      priceDelta: "가격 변동",
      listPrice: "정가",
      finalPrice: "최종 가격",
      savings: "절감액",
      autoNegotiate: "자동 협상 (AI)",
      noNegotiations: "아직 협상이 없습니다",
      noNegotiationsDesc: "새 협상을 시작하면 AI 에이전트가 실시간으로 흥정합니다.",
      policyLimit: "정책 예산 한도",
    },
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (path: string) => {
    const keys = path.split('.');
    let current: any = translations[language];
    for (const key of keys) {
      if (current[key] === undefined) {
        console.warn(`Translation missing for key: ${path} in language: ${language}`);
        return path;
      }
      current = current[key];
    }
    return current;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
